version: '2.2'

services:
  android:
    image: budtmo/docker-android:emulator_14.0
    network_mode: "service:react-native-dev"
    environment:
      - DATAPARTITION=4g
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    privileged: true
    depends_on:
      - react-native-dev
  react-native-dev:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./app/android/gradle:/app/.gradle
    working_dir: /app
    command: "/bin/bash -c 'npm i && npm run android'"
    ports: 
      - "6080:6080" #from android service
      
    tty: true
    stdin_open: true
    container_name: react-native-dev
     
volumes:
  gradle: