version: '3.8'
services:
 android:
    image: budtmo/docker-android:emulator_11.0_v2.0
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm:/dev/kvm
    
    working_dir: /home/androidusr/tmp
    command: "/bin/bash -c './gradlew build'"
    

    privileged: true
    ports: 
      - "6080:6080" #from android service    
    tty: true
    stdin_open: true
    container_name: react-native-dev