name: Terraform Test


on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

  # Schedule the job to everyday to refresh dynamic first page
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run deploy script file 
      run: |
         chmod +x ./scripts/deploy.sh
         ./scripts/deploy.sh
      shell: bash
    - name: Run destroy script file 
      run: |
         chmod +x ./scripts/destroy.sh
         ./scripts/destroy.sh
      shell: bash



 